app/routes.php
    Route::get('inventories/discontinued/follmer', 'InventoriesController@follmer_discontinued');
    Route::get('inventories/discontinued/flavors', 'InventoriesController@flavors_discontinued');
    Route::get('inventories/discontinued/flavors_for_samples', 'InventoriesController@flavors_for_samples_discontinued');
    Route::get('inventories/discontinued/customers_oils', 'InventoriesController@customers_oils_discontinued');

    //pdf
    Route::get('inventories/pdf/product_totals', 'InventoriesController@pdf_product_totals');
    Route::get('inventories/pdf/drums', 'InventoriesController@pdf_drum');
    Route::get('inventories/pdf/totes', 'InventoriesController@pdf_totes');
    Route::get('inventories/pdf/organics', 'InventoriesController@pdf_organic');
    Route::get('inventories/pdf/tanks', 'InventoriesController@pdf_tanks');
    Route::get('inventories/pdf/vinegars', 'InventoriesController@pdf_vinegars');
    Route::get('inventories/pdf/railcars', 'InventoriesController@pdf_railcars');
    Route::get('inventories/pdf/specialty', 'InventoriesController@pdf_specialty');
    Route::get('inventories/pdf/infused_oil_drums', 'InventoriesController@pdf_infused_oil_drum');
    Route::get('inventories/pdf/spreads_and_olives', 'InventoriesController@pdf_spreads_and_olive_oils');
    Route::get('inventories/pdf/website_olive_oils', 'InventoriesController@pdf_website_olive_oil');
    Route::get('inventories/pdf/web_flavor_and_infused', 'InventoriesController@pdf_web_flavor_and_infused');
    Route::get('inventories/pdf/website_vinegars', 'InventoriesController@pdf_website_vinegar');
    Route::get('inventories/pdf/website_other', 'InventoriesController@pdf_website_other');
    Route::get('inventories/pdf/website_totals', 'InventoriesController@pdf_website_totals');
    Route::get('inventories/pdf/finished_product', 'InventoriesController@pdf_finished_product');
    Route::get('inventories/pdf/sprays', 'InventoriesController@pdf_spray');
    Route::get('inventories/pdf/ready_to_ship', 'InventoriesController@pdf_ready_to_ship');
    Route::get('inventories/pdf/rework', 'InventoriesController@pdf_rework');
    Route::get('inventories/pdf/labels_in_house', 'InventoriesController@pdf_labels_in_house');
    Route::get('inventories/pdf/labels_in_labelroom', 'InventoriesController@pdf_labels_in_labelroom');
    Route::get('inventories/pdf/customers_labels', 'InventoriesController@pdf_customers_labels');
    Route::get('inventories/pdf/bottles', 'InventoriesController@pdf_bottle');
    Route::get('inventories/pdf/etched_bottles', 'InventoriesController@pdf_etched_bottle');
    Route::get('inventories/pdf/fustis', 'InventoriesController@pdf_fustis');
    Route::get('inventories/pdf/caps', 'InventoriesController@pdf_cap');
    Route::get('inventories/pdf/cardboard_blank', 'InventoriesController@pdf_cardboard_blank');
    Route::get('inventories/pdf/cardboard_printed', 'InventoriesController@pdf_cardboard_printed');
    Route::get('inventories/pdf/supply', 'InventoriesController@pdf_supply');
    Route::get('inventories/pdf/materials', 'InventoriesController@pdf_material');
    Route::get('inventories/pdf/follmer', 'InventoriesController@pdf_follmer');
    Route::get('inventories/pdf/flavors', 'InventoriesController@pdf_flavor');
    Route::get('inventories/pdf/flavors_for_samples', 'InventoriesController@pdf_flavors_for_sample');
    Route::get('inventories/pdf/inventory_totals', 'InventoriesController@pdf_inventory_totals');
    Route::get('inventories/pdf/totals_for_bank', 'InventoriesController@pdf_totals_for_bank');
    Route::get('inventories/pdf/customers_oils', 'InventoriesController@pdf_customers_oils');

    //specsheets pdf
    Route::get('specsheets/pdf/specsheets/{id}','SpecsheetsController@pdf_specsheets');

    Route::resource('inventories', 'InventoriesController');

    //

    /*
    *Product Hold
    *
    */

    Route::get('productholds/released', 'ProductholdsController@released');
    Route::resource('productholds', 'ProductholdsController');
    //Product Hold release

    /*
    *RMA Form
    *
    */
    Route::resource('rmas', 'RmasController');



    /*
    *Receiving Logs 2016
    *
    */
     //label
    // Route::get('receivinglogs2016/label/{id}', 'Receivinglog2016Controller@label');




    /*
     * Samples
     * Remove Per Josh
     */
//    Route::resource('samples', 'SamplesController');

    /*
    *Freight Quotes
    * per Leeanne
    */
    Route::resource('freightquotes', 'FreightquotesController');
    /*
     * Shipping
     */
    Route::get('shippings/shipped', 'ShippingsController@shipped');
    Route::resource('shippings', 'ShippingsController');
    /*
     * Appointment Logs
     *
     */
    Route::get('receivingappointmentlogs/received', 'ReceivingappointmentlogsController@received');
    Route::resource('receivingappointmentlogs', 'ReceivingappointmentlogsController');

//blends
    Route::resource('blends', 'BlendsController');

/*
* COA
*
*/

Route::resource('coas', 'CoasController');

/*
 * Lot Logs
 * Material Lot Logs
 */

    // Route::get('lotlogs/label_store/{id}', 'LotlogsController@label_store');

    Route::post('lotlogs/label/{id}', 'LotlogsController@label_store');
    Route::get('lotlogs/label/{id}', 'LotlogsController@label');

    Route::get('lotlogs/label/print', 'LotlogsController@label_store');
    Route::get('lotlogs/in_progress', 'LotlogsController@in_progress');
    Route::get('lotlogs/archive', 'LotlogsController@archive');
    Route::get('lotlogs/last_year', 'LotlogsController@last_year');
    Route::get('lotlogs/all', 'LotlogsController@all');
    Route::resource('lotlogs', 'LotlogsController');

//material lot logs
    Route::post('materiallotlogs/label/{id}', 'MateriallotlogsController@label_store');
    Route::get('materiallotlogs/label/{id}', 'MateriallotlogsController@label');

    Route::get('materiallotlogs/label/print', 'MateriallotlogsController@label_store');
    Route::resource('materiallotlogs', 'MateriallotlogsController');

//specsheets
    Route::resource('specsheets', 'SpecsheetsController');

//spotcheck
    Route::get('spotchecks/print', 'SpotchecksController@print_page');
    Route::resource('spotchecks', 'SpotchecksController');

//old app for Karen
//    Route::resource('salescharts', 'SaleschartsController');

//nutritionfacts
    Route::resource('nutritionfacts', 'NutritionfactsController');

    /**
     * Receiving Logs
     */

//2013 receiving log print
    Route::get('receivinglogs/print', 'ReceivinglogsController@print_page');
    Route::resource('receivinglogs', 'ReceivinglogsController');

//2012 receiving log print
    Route::get('recievinglog2012s/print', 'Receivinglog2012sController@print_page');
    Route::resource('receivinglog2012s', 'Receivinglog2012sController');

//2014 receiving log print
    Route::get('recievinglog2014s/print', 'Recievinglog2014sController@print_page');
    Route::resource('recievinglog2014s', 'Recievinglog2014sController');

//2015 receiving log print
    Route::get('recievinglog2015s/print', 'Recievinglog2015sController@print_page');
    Route::resource('recievinglog2015s', 'Recievinglog2015sController');

//2016 receiving log print
    Route::get('receivinglogs2016/print', 'Receivinglog2016Controller@print_page');
    Route::resource('receivinglogs2016', 'Receivinglog2016Controller');

//2017 receiving log
    Route::get('receivinglogs2017/print', 'Receivinglog2017Controller@print_page');
    Route::resource('receivinglogs2017', 'Receivinglog2017Controller');

//2018 receiving log
    Route::get('receivinglogs2018/print', 'Receivinglog2018Controller@print_page');
    Route::resource('receivinglogs2018', 'Receivinglog2018Controller');


//customer complaints
    //customer complaints api
    //form from store supply
    Route::post('api/customercomplaints', 'CustomercomplaintsController@api_store');
    //
    // qc report
    // Route::get('customercomplaints/concern_report', 'CustomercomplaintsController@concern_report');
    Route::get('customercomplaints/concern_report/{id}', 'CustomercomplaintsController@concern_report');

    //
    Route::resource('products', 'ProductsController');

    Route::get('customercomplaints/reports', 'CustomercomplaintsController@reports');
    Route::get('customercomplaints/qc', 'CustomercomplaintsController@qc');
    Route::get('customercomplaints/customer_service', 'CustomercomplaintsController@customer_service');
    Route::get('customercomplaints/production', 'CustomercomplaintsController@production');
    Route::get('customercomplaints/technology', 'CustomercomplaintsController@technology');
    Route::get('customercomplaints/{id}/products', 'CustomercomplaintsController@products');
    Route::post('customercomplaints/{id}/products', 'CustomercomplaintsController@products');
    Route::get('customercomplaints/complete', 'CustomercomplaintsController@complete');
    Route::get('customercomplaints/in_progress', 'CustomercomplaintsController@in_progress');
    Route::get('customercomplaints/last_year', 'CustomercomplaintsController@last_year'); 
    Route::resource('customercomplaints', 'CustomercomplaintsController');
//PO ETA's
    Route::get('poetas/archive', 'PoetasController@archive');
    Route::resource('poetas', 'PoetasController');


    //insert products into customer complaints
    // Route::get('customercomplaints', function(){
    //         $customer =  Customercomplaint::find(1);

    //         $customer->products()->insert([
    //                 'product_description' => 'This is a description',
    //                 'customercomplaint_id' => $customer->id
    //             ]);

    //         foreach ($customer->products as $product) {
    //             return $product->product_description;
    //         }

           
    // });

//orders
    Route::get('orders', 'OrdersController@index');


//user
    Route::resource('user', 'UserController');
//admin/backend section
    Route::controller('admin', 'AdminController');
});

app/models/Customercomplaint.php
<?php

class Customercomplaint extends \Eloquent {

	// Add your validation rules here
	public static $rules = [
		// 'title' => 'required'
		'date_of_complaint' => 'required'
	];

	public function products(){
		return $this->hasMany('Product');
	}

	// Don't forget to fill this array
	protected $fillable = [
		'id',
		'customercomplaint_id',
		'status',
		'case_number',
		'customer_name',
		'customer_contact',
		'customer_email',
		'order_number',
		'ship_date',
		'date_of_complaint',
		'time_of_complaint',
		'return_received_by',
		'complaint_received_by',
		'customer_phone',
		'customer_fax',
		'verbal',
		'details_of_complaint',
		'first_action_taken_notes',
		'first_action_taken_by',
		'first_action_taken_date',
		'first_action_taken_time',
		'corrective_action_notes',
		'corrective_action_by',
		'corrective_action_date',
		'corrective_action_time',
		'credit_return_replacement_authorization',
		'credit_return_replacement_authorization_by',
		'fifteen_restocking_fee',
		'fifteen_restocking_fee_amount',
		'ups_cost_to_re_ship',
		'return_received',
		'complaint_received_via',
		'received_by',
		'created_at',
		'updated_at',
		'freight_damage_ups',
		'freight_damage_other',
		'quality_of_product',
		'wrong_missing_product',
		'labeling_documentation',
		'other',
		'ups_freight_refund',
	];

}

app/views/customercomplaints/complete.blade.php
@extends('layouts.admin')

@section('content')

<div id="specsheets">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                <span class="alert alert-dismissible alert-success" style="padding-right:15px;">Complete</span>Customer Complaints {{ Date("Y") }}
            </h1>
            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> <a href="/admin">Dashboard</a> > Customer Complaints
                </li>
            </ol>
        </div>
    </div>

    {{--sessions--}}
    @if(Session::has('message'))
        <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
    @endif

    {{--sub nav--}}
    <div class="row">
        <div class="col-lg-12">
            <nav class="navbar navbar-default">
                {{ link_to_route('customercomplaints.index', 'Back To Customer Complaints',null, ['class' => 'btn btn-primary navbar-btn']) }}                {{--search--}}

                {{-- <form class="navbar-form navbar-right" role="search">
                    <div class="form-group">
                        <input type="text" class=" search form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-primary" data-sort="nutritionfact">Submit</button>
                </form> --}}
            </nav>
        </div>
    </div>

    <table class="table table-stripped table-responsive table-hover" id="datatable">
        <thead>
        <tr>
           <td><strong>Case Number</strong>
           <td><strong>Date Of Complaint</strong></td>
           <td><strong>Company Name</strong></td>
           <td><strong>Customer Contact</strong></td>
           <td><strong>Order Number</strong></td>
           <td class="no-sort"></td>
        </tr>
        </thead>
        <tbody class="list">
        @foreach($customercomplaints as $customercomplaint)
            @if($customercomplaint->status == 'complete')
            <tr>
            <td class="casenumber">
            <?php $case_number = $customercomplaint->id + 200 ?>
            {{ $case_number }}
            </td>
             <td class="isdone">{{ $customercomplaint->customer_name }}</td>
             <td>{{ $customercomplaint->date_of_complaint }}</td>
             <td>{{ $customercomplaint->customer_contact }}</td>
             <td class="ordernumber">{{ $customercomplaint->order_number }}</td>
             <td>
                 <a href="/customercomplaints/{{ $customercomplaint->id }}/products" class="btn btn-primary">Products</a>
             </td>
            </tr>
            @endif
        @endforeach

        </tbody>
    </table>


<ul class="pagination"></ul>
</div>
    @stop

{{--end content--}}


{{--footer--}}
@section('footer')
<script>
              $(function() {
            $( "#datepicker" ).datepicker();
            $( "#datepicker1" ).datepicker();
            $('#timepicker').timepicker();
            $('#datatable').DataTable({
                paging:true,
                "order": [[ 0, "desc" ]],
                // scrollY:400,
                deferRender:true,
                // scroller:true,
                columnDefs: [
                                { targets: 'no-sort', orderable: false }
                            ],

            });
        });

    </script>
    @stop

app/views/customercomplaints/customer_service.blade.php
@extends('layouts.admin')

@section('content')

<div id="specsheets">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Customer Complaints > Customer Service
            </h1>
            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> <a href="/admin">Dashboard</a> > <a href="/customercomplaints">Customer Complaints</a> > Customer Service
                </li>
            </ol>
        </div>
    </div>

    {{--sessions--}}
    @if(Session::has('message'))
        <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
    @endif

    {{--sub nav--}}
    <div class="row">
        <div class="col-lg-12">
            <nav class="navbar navbar-default">
              {{ link_to_route('customercomplaints.create', 'Create A New Customer Complaint',null, ['class' => 'btn btn-primary navbar-btn']) }}                {{--search--}}
              <a href="/customercomplaints/in_progress" class="btn btn-yellow navbar-btn">In Progress</a>
              <a href="/customercomplaints/complete" class="btn btn-success navbar-btn">Complete</a>

              <a href="/customercomplaints/customer_service" class="btn btn-customer-service navbar-btn">Customer Service</a>
              <a href="/customercomplaints/production" class="btn btn-production navbar-btn">Production</a>
              <a href="/customercomplaints/qc" class="btn btn-warning navbar-btn">Q.C.</a>
              <a href="/customercomplaints/technology" class="btn btn-technology navbar-btn">Technology</a>

                {{-- <form class="navbar-form navbar-right" role="search">
                    <div class="form-group">
                        <input type="text" class=" search form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-primary" data-sort="nutritionfact">Submit</button>
                </form> --}}
            </nav>
        </div>
    </div>

    <table class="table table-stripped table-responsive table-hover" id="datatable">
        <thead>
        <tr>
          <td><strong>Status</strong></td>
           <td><strong>Case Number</strong>
           <td><strong>Date Of Complaint</strong></td>
           <td><strong>Corrective Action By</strong></td>
           <td><strong>Company Name</strong></td>
           <td><strong>Customer Contact</strong></td>
           <td><strong>Order Number</strong></td>
           <td class="no-sort"></td>
        </tr>
        </thead>
        <tbody class="list">


        @foreach($customer_service as $customercomplaint)
        @if($customercomplaint->corrective_action_by == 'Customer Service')
            @if($customercomplaint->status == 'in_progress')
            <tr style="background-color:#faff8c;font-weight:bold;">
            @elseif($customercomplaint->status == 'complete')
            <tr style="background-color:#abcca1;font-weight:bold;">
            @else
              <tr>
            @endif
            <td class="status">
              @if($customercomplaint->status == 'in_progress')
                In Progress
              @elseif($customercomplaint->status == 'complete')
                Complete
              @endif

            </td>
            <td class="casenumber">
            <?php $customer_number = $customercomplaint->id + 200; ?>
            {{ $customer_number }}
            </td>
            <td>{{ $customercomplaint->date_of_complaint }}</td>
            @if($customercomplaint->corrective_action_by == 'QC')
            <td style="background: orange;border:3px solid black; color: white;">
            @elseif($customercomplaint->corrective_action_by == 'Production')
            <td style="background: brown;border:3px solid black;color: white">
            @elseif($customercomplaint->corrective_action_by == 'Technology')
            <td style="background: grey;border:3px solid black; color: white;">
            @elseif($customercomplaint->corrective_action_by == 'Customer Service')
            <td style="background: pink; border: 3px solid black">
            @else
            <td>
            @endif
            {{ $customercomplaint->corrective_action_by }}</td>

             <td class="isdone">{{ $customercomplaint->customer_name }}</td>
             <td>{{ $customercomplaint->customer_contact }}</td>
             <td class="ordernumber">{{ $customercomplaint->order_number }}</td>
             <td class="no-sort">
                 <div class="btn-group" role="group" aria-label="">
                 <a href="/customercomplaints/{{ $customercomplaint->id }}/products" class="btn btn-primary">Products</a>
                     {{ link_to_route('customercomplaints.show', 'View', [$customercomplaint->id],['class' => 'btn btn-success']) }}
                     @if(Auth::user()->group == 100)
                     {{ link_to_route('customercomplaints.edit', 'Edit', [$customercomplaint->id],['class' => 'btn btn-warning']) }}

                     {{ Form::open(array('method' => 'DELETE', 'style' => 'display:inline','route' => array('customercomplaints.destroy', $customercomplaint->id))) }}
                     {{ Form::submit('Delete', ['class' => 'btn btn-danger']) }}
                     {{ Form::close() }}
                     @endif
                 </div>
             </td>
            </tr>
            @endif
        @endforeach

        </tbody>
    </table>


<ul class="pagination"></ul>
</div>
    @stop

{{--end content--}}


{{--footer--}}
@section('footer')
    <script>
              $(function() {
            $( "#datepicker" ).datepicker();
            $( "#datepicker1" ).datepicker();
            $('#timepicker').timepicker();
            $('#datatable').DataTable({
                paging:true,
                "order": [[ 1, "desc" ]],
                // scrollY:400,
                deferRender:true,
                // scroller:true,
                columnDefs: [
                                { targets: 'no-sort', orderable: false }
                            ],

            });
        });

    </script>
    @stop

app/views/customercomplaints/in_progress.blade.php
@extends('layouts.admin')

@section('content')

<div id="specsheets">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                <span class="alert alert-dismissible alert-success" style="padding-right:15px;">In Progress</span>Customer Complaints {{ Date("Y") }}
            </h1>
            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> <a href="/admin">Dashboard</a> > Customer Complaints
                </li>
            </ol>
        </div>
    </div>

    {{--sessions--}}
    @if(Session::has('message'))
        <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
    @endif

    {{--sub nav--}}
    <div class="row">
        <div class="col-lg-12">
            <nav class="navbar navbar-default">
                {{ link_to_route('customercomplaints.index', 'Back To Customer Complaints',null, ['class' => 'btn btn-primary navbar-btn']) }}                {{--search--}}

                {{-- <form class="navbar-form navbar-right" role="search">
                    <div class="form-group">
                        <input type="text" class=" search form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-primary" data-sort="nutritionfact">Submit</button>
                </form> --}}
            </nav>
        </div>
    </div>

    <table class="table table-stripped table-responsive table-hover" id="datatable">
        <thead>
        <tr>
           <td><strong>Case Number</strong>
           <td><strong>Company Name</strong></td>
           <td><strong>Customer Contact</strong></td>
           <td><strong>Order Number</strong></td>
           <td><strong>Date Of Complaint</strong></td>
           <td></td>
        </tr>
        </thead>
        <tbody class="list">
        @foreach($customercomplaints as $customercomplaint)
        @if($customercomplaint->status == 'in_progress')
            <tr>
            <td class="casenumber">
            <?php $case_number = $customercomplaint->id + 200; ?>
            {{ $case_number }}
            </td>
             <td class="isdone">{{ $customercomplaint->customer_name }}</td>
             <td>{{ $customercomplaint->customer_contact }}</td>
             <td class="ordernumber">{{ $customercomplaint->order_number }}</td>
             <td>{{ $customercomplaint->date_of_complaint }}</td>
             <td>
                 <div class="btn-group" role="group" aria-label="">
                <a href="/customercomplaints/{{ $customercomplaint->id }}/products" class="btn btn-primary">Products</a>
                     {{ link_to_route('customercomplaints.show', 'View', [$customercomplaint->id],['class' => 'btn btn-success']) }}
                     @if(Auth::user()->group == 100)
                     {{ link_to_route('customercomplaints.edit', 'Edit', [$customercomplaint->id],['class' => 'btn btn-warning']) }}

{{--                      {{ Form::open(array('method' => 'DELETE', 'style' => 'display:inline','route' => array('customercomplaints.destroy', $customercomplaint->id))) }}
                     {{ Form::submit('Delete', ['class' => 'btn btn-danger']) }}
                     {{ Form::close() }} --}}
                     @endif
                 </div>
             </td>
            </tr>
            @endif
        @endforeach

        </tbody>
    </table>


<ul class="pagination"></ul>
</div>
    @stop

{{--end content--}}


{{--footer--}}
@section('footer')
    <script>
              $(function() {
            $( "#datepicker" ).datepicker();
            $( "#datepicker1" ).datepicker();
            $('#timepicker').timepicker();
            $('#datatable').DataTable({
                paging:true,
                "order": [[ 0, "desc" ]],
                // scrollY:400,
                deferRender:true,
                // scroller:true,
                columnDefs: [
                                { targets: 'no-sort', orderable: false }
                            ],

            });
        });

    </script>
    @stop

app/views/customercomplaints/index.blade.php
@extends('layouts.admin')

@section('content')

<div id="specsheets">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Customer Complaints {{ Date("Y") }}
            </h1>
            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> <a href="/admin">Dashboard</a> > Customer Complaints
                </li>
            </ol>
        </div>
    </div>

    {{--sessions--}}
    @if(Session::has('message'))
        <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
    @endif

    {{--sub nav--}}
    <div class="row">
        <div class="col-lg-12">
            <nav class="navbar navbar-default">
              {{ link_to_route('customercomplaints.create', 'Create A New Customer Complaint',null, ['class' => 'btn btn-primary navbar-btn']) }}                {{--search--}}
              <a href="/customercomplaints/in_progress" class="btn btn-yellow navbar-btn">In Progress</a>
              <a href="/customercomplaints/complete" class="btn btn-success navbar-btn">Complete</a>

              <a href="/customercomplaints/customer_service" class="btn btn-customer-service navbar-btn">Customer Service</a>
              <a href="/customercomplaints/production" class="btn btn-production navbar-btn">Production</a>
              <a href="/customercomplaints/qc" class="btn btn-warning navbar-btn">Q.C.</a>
              <a href="/customercomplaints/technology" class="btn btn-technology navbar-btn">Technology</a>
              <a href="/customercomplaints/reports" class="btn btn-primary navbar-btn">Reports</a>

                {{-- <form class="navbar-form navbar-right" role="search">
                    <div class="form-group">
                        <input type="text" class=" search form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-primary" data-sort="nutritionfact">Submit</button>
                </form> --}}
            </nav>
        </div>
    </div>

    <table class="table table-stripped table-responsive table-hover" id="datatable">
        <thead>
        <tr>
          <td><strong>Status</strong></td>
           <td><strong>Case Number</strong>
           <td><strong>Date Of Complaint</strong></td>
           <td><strong>Corrective Action By</strong></td>
           <td><strong>Company Name</strong></td>
           <td><strong>Details of Complaint</strong></td>
           <td><strong>Order Number</strong></td>
           <td class="no-sort"></td>
        </tr>
        </thead>
        <tbody class="list">


        @foreach($customercomplaints as $customercomplaint)
            @if($customercomplaint->status == 'in_progress')
            <tr style="background-color:#faff8c;font-weight:bold;">
            @elseif($customercomplaint->status == 'complete')
            <tr style="background-color:#abcca1;font-weight:bold;">
            @else
              <tr>
            @endif
            <td class="status">
              @if($customercomplaint->status == 'in_progress')
                In Progress
              @elseif($customercomplaint->status == 'complete')
                Complete
              @endif

            </td>
            <td class="casenumber">
            <?php $customer_number = $customercomplaint->id + 200; ?>
            {{ $customer_number }}
            </td>
            <td>{{ $customercomplaint->date_of_complaint }}</td>
            @if($customercomplaint->corrective_action_by == 'QC')
            <td style="background: orange;border:3px solid black; color: white;">
            @elseif($customercomplaint->corrective_action_by == 'Production')
            <td style="background: brown;border:3px solid black;color: white">
            @elseif($customercomplaint->corrective_action_by == 'Technology')
            <td style="background: grey;border:3px solid black; color: white;">
            @elseif($customercomplaint->corrective_action_by == 'Customer Service')
            <td style="background: pink; border: 3px solid black">
            @else
            <td>
            @endif
            @if($customercomplaint->corrective_action_by == '0')
            Not Assigned
            @else
            {{ $customercomplaint->corrective_action_by }}
            </td>
            @endif
             <td class="isdone">{{ $customercomplaint->customer_name }}</td>
             <td>{{ $customercomplaint->details_of_complaint }}</td>
             <td class="ordernumber">{{ $customercomplaint->order_number }}</td>
             <td class="no-sort">
                 <div class="btn-group" role="group" aria-label="">
                 <a href="/customercomplaints/{{ $customercomplaint->id }}/products" class="btn btn-primary">Products</a>
                 <a href="/customercomplaints/concern_report/{{ $customercomplaint->id}}" class="btn btn-technology">Download</a>
                     {{ link_to_route('customercomplaints.show', 'View', [$customercomplaint->id],['class' => 'btn btn-success']) }}
                     @if(Auth::user()->group == 100)
                     {{ link_to_route('customercomplaints.edit', 'Edit', [$customercomplaint->id],['class' => 'btn btn-warning']) }}

                     {{ Form::open(array('method' => 'DELETE', 'style' => 'display:inline','route' => array('customercomplaints.destroy', $customercomplaint->id))) }}
                     {{ Form::submit('Delete', ['class' => 'btn btn-danger']) }}
                     {{ Form::close() }}
                     @endif
                 </div>
             </td>
            </tr>
        @endforeach

        </tbody>
    </table>


<ul class="pagination"></ul>
</div>
    @stop

{{--end content--}}


{{--footer--}}
@section('footer')
    <script>
              $(function() {
            $( "#datepicker" ).datepicker();
            $( "#datepicker1" ).datepicker();
            $('#timepicker').timepicker();
            $('#datatable').DataTable({
                paging:true,
                "order": [[ 1, "desc" ]],
                // scrollY:400,
                deferRender:true,
                // scroller:true,
                columnDefs: [
                                { targets: 'no-sort', orderable: false }
                            ],

            });
        });

    </script>
    @stop